### ISSUE TITLE
关于“发帖时间间隔”

### ISSUE THREAD

**Issue by maidmeow4** [MoeNetwork/wmzz_post#1]
“发帖时间间隔”处假若我设定了一个较高的数值（比如70秒），我是否需要调整`php.ini`中PHP程序最大运行时间（`max_execution_time`）？

**Comment by balthild** [comment]
发帖间隔和最大运行时间似乎没有什么关联的吧……？ 

@kenvix

**Comment by cuteSakuraHime** [comment]
不需要
