### ISSUE TITLE
为什么会出现权限不足？

### ISSUE THREAD

**Issue by kuilei0926** [MoeNetwork/wmzz_post#2]
运行/plugins/wmzz_post/wmzz_post_cron.php时出现Insufficient Permissions。。

**Comment by kuilei0926** [comment]
![qq 20161001213845](https://cloud.githubusercontent.com/assets/17094610/19014455/9f89e00c-881f-11e6-9002-9a3498c81f6b.png)

**Comment by balthild** [comment]
@kenvix 背锅

**Comment by kenvix** [comment]
（╯‵□′）╯︵┴─┴
