### ISSUE TITLE
sql错误

### ISSUE THREAD

**Issue by TwilightHome** [MoeNetwork/wmzz_post#3]
消息：#10000 - MySQL 语句执行错误：
语句：SELECT COUNT(*) AS `c` FROM `tc_wmzz_post_data` WHERE `remain` > '0' LIMIT ;
错误：#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

tieba/lib/class.mysqli.php | 120 | [抛出异常]
tieba/lib/class.mysqli.php | 160 | query
tieba/plugins/wmzz_post/wmzz_post_cron.php | 106 | once_fetch_array
  |   | cron_wmzz_post
tieba/lib/class.cron.php | 192 | call_user_func
tieba/setting.php | 449 | run

帖子云灌水设置保存时失败,出现页面载入出错,连接失败

  | 失败，#110001 : 未知错误

**Comment by juzeon** [comment]
这个问题我也遇到了，就在php7上会有这个异常。php5.6测试正常

**Comment by ghost** [comment]
我也遇到了。作者还更新这个插件吗？

**Comment by cuteSakuraHime** [comment]
这个插件是开源的，你们可以自己修改。作者在开新坑，应该是不会更新了。

**Comment by kenvix** [comment]
请修改云灌水设置就可以了，老bug了
